name: Platformio
on: [workflow_dispatch, push]

env:
  TARGET: nodemcuv2 # Must match the value after colon in platformio.ini (line 4: [env:nodemcuv2])
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: pio run -e ${{ env.TARGET }}
    - name: Archive Firmware Files
      uses: actions/upload-artifact@v3
      with: 
        path: .pio/build/${{ env.TARGET }}/firmware.bin

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Download Firmware Files
      uses: actions/download-artifact@v3

    - name: Release Firmware
      uses: ncipollo/release-action@v1
      with:
        artifacts: ./artifact/firmware.bin
        generateReleaseNotes: true
        allowUpdates: true